jobs:
  codenotify:
    name: Label and notify
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        show-progress: false
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: sourcegraph/codenotify@v0.6.4
    - continue-on-error: true
      uses: actions/labeler@v4.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: codenotify
on:
  repository_dispatch:
    types: trigger-ga___codenotify.yml
