env:
  CONTINUOUS_INTEGRATION: true
  MAVEN_FAST_INSTALL: -B -V --quiet -T 1C -DskipTests -Dair.check.skip-all --no-transfer-progress
    -Dmaven.javadoc.skip=true
  MAVEN_INSTALL_OPTS: -Xmx2G -XX:+ExitOnOutOfMemoryError
  MAVEN_OPTS: -Xmx1024M -XX:+ExitOnOutOfMemoryError
  MAVEN_TEST: -B -Dair.check.skip-all -Dmaven.javadoc.skip=true -DLogTestDurationListener.enabled=true
    --no-transfer-progress --fail-at-end
  RETRY: .github/bin/retry
jobs:
  changes:
    outputs:
      codechange: ${{ steps.filter.outputs.codechange }}
    permissions:
      pull-requests: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: "codechange:\n  - '!presto-docs/**'\n"
  spark-integration:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-spark-integration-${{ github.event.pull_request.number
        }}
    if: needs.changes.outputs.codechange == 'true'
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        show-progress: false
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      id: cache-maven
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-2-

          '
    - continue-on-error: true
      if: steps.cache-maven.outputs.cache-hit != 'true'
      name: Populate maven cache
      run: ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies --no-transfer-progress
        && .github/bin/download_nodejs
    - continue-on-error: true
      name: Maven Install
      run: 'export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"

        ./mvnw install ${MAVEN_FAST_INSTALL} -am -pl presto-spark-launcher,presto-spark-package,presto-spark-testing

        '
    - continue-on-error: true
      name: Maven Tests
      run: ./mvnw test ${MAVEN_TEST} -pl :presto-spark-testing -P test-presto-spark-integration-smoke-test
    timeout-minutes: 60
name: spark integration
on:
  repository_dispatch:
    types: trigger-ga___spark-integration.yml
