env:
  CONTINUOUS_INTEGRATION: true
  MAVEN_FAST_INSTALL: -B -V --quiet -T 1C -DskipTests -Dair.check.skip-all --no-transfer-progress
    -Dmaven.javadoc.skip=true
  MAVEN_INSTALL_OPTS: -Xmx2G -XX:+ExitOnOutOfMemoryError
  MAVEN_OPTS: -Xmx1024M -XX:+ExitOnOutOfMemoryError
  MAVEN_TEST: -B -Dair.check.skip-all -Dmaven.javadoc.skip=true -DLogTestDurationListener.enabled=true
    --no-transfer-progress --fail-at-end
  RETRY: .github/bin/retry
jobs:
  changes:
    outputs:
      codechange: ${{ steps.filter.outputs.codechange }}
    permissions:
      pull-requests: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: "codechange:\n  - '!presto-docs/**'\n"
  test:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-test-${{ matrix.modules }}-${{ github.event.pull_request.number
        }}
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: needs.changes.outputs.codechange == 'true'
      uses: actions/checkout@v4
      with:
        show-progress: false
    - continue-on-error: true
      if: needs.changes.outputs.codechange == 'true'
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      id: cache-maven
      if: needs.changes.outputs.codechange == 'true'
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-2-

          '
    - continue-on-error: true
      if: steps.cache-maven.outputs.cache-hit != 'true' && needs.changes.outputs.codechange
        == 'true'
      name: Populate maven cache
      run: ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies --no-transfer-progress
        && .github/bin/download_nodejs
    - continue-on-error: true
      if: needs.changes.outputs.codechange == 'true'
      name: Maven Install
      run: 'export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"

        ./mvnw install ${MAVEN_FAST_INSTALL} -am -pl $(echo ''${{ matrix.modules }}''
        | cut -d'' '' -f1)

        '
    - continue-on-error: true
      if: needs.changes.outputs.codechange == 'true'
      name: Maven Tests
      run: ./mvnw test ${MAVEN_TEST} -pl ${{ matrix.modules }}
    strategy:
      fail-fast: false
      matrix:
        modules:
        - :presto-tests -P presto-tests-execution-memory
        - :presto-tests -P presto-tests-general
        - :presto-tests -P ci-only-distributed-non-hash-gen
        - :presto-tests -P ci-only-tpch-distributed-queries
        - :presto-tests -P ci-only-local-queries
        - :presto-tests -P ci-only-distributed-queries
        - :presto-tests -P ci-only-aggregation-queries
        - :presto-tests -P ci-only-plan-determinism
        - :presto-tests -P ci-only-resource-manager
        - :presto-accumulo
        - :presto-cassandra -P test-cassandra-integration-smoke-test
        - :presto-hive
        - :presto-hive -P test-hive-materialized-queries
        - :presto-hive -P test-hive-materialized-aggregations
        - :presto-hive -P test-hive-recoverable-execution
        - :presto-hive -P test-hive-pushdown-filter-queries-basic
        - :presto-hive -P test-hive-pushdown-filter-queries-advanced
        - :presto-hive -P test-hive-repartitioning
        - :presto-hive -P test-hive-parquet
        - :presto-main
        - :presto-mongodb -P test-mongo-distributed-queries
        - :presto-redis -P test-redis-integration-smoke-test
        - :presto-elasticsearch
        - :presto-orc
        - :presto-thrift-connector
        - :presto-spark-base -P presto-spark-tests-smoke
        - :presto-spark-base -P presto-spark-tests-all-queries
        - :presto-spark-base -P presto-spark-tests-spill-queries
        - :presto-iceberg
    timeout-minutes: 80
name: test
on:
  repository_dispatch:
    types: trigger-ga___tests.yml
