env:
  CONTINUOUS_INTEGRATION: true
  RETRY: .github/bin/retry
jobs:
  changes:
    outputs:
      codechange: ${{ steps.filter.outputs.codechange }}
    permissions:
      pull-requests: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: "codechange:\n  - '!presto-docs/**'\n  - 'presto-ui/**'\n"
  web-ui-checks:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-web-ui-checks-${{ github.event.pull_request.number
        }}
    if: needs.changes.outputs.codechange == 'true'
    needs: changes
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        show-progress: false
    - continue-on-error: true
      name: Web UI Checks
      run: presto-ui/bin/check_webui.sh
    timeout-minutes: 30
name: web ui checks
on:
  repository_dispatch:
    types: trigger-ga___web-ui-checks.yml
